spring:
  application:
    name: ecommerce-service

  datasource:
    url: jdbc:h2:mem:javatpoint
    driverClassName: org.h2.Driver
    username: Chida007
    password: chida

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      path: /h2-console
      enabled: true
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: ERROR
    com.ecommerce: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n%ex{full}"
  exception-conversion-word: "%ex{full}"
  include-application-name: false
jwt:
  tokenSecret: KF/JLEjRhf+sAKdBCgG+p2yT3i90UfGNJjO/133SVTWGxVS9sAycAFn26rtJNAZXyPO3LDUE1BeK+JNvIDllbA==
  validityInDays: 7
